### PR TITLE
Release 1.10.15-1.dev

### PR DESCRIPTION
**Pull request by ernest-kr**
**What this PR does / why we need it**:
Releasing 1.10.15-1.dev
Tag: https://github.com/astronomer/airflow/releases/tag/v1.10.15%2Bastro.1

### CODE REVIEW

**Review by danielhoherd — APPROVED** [review]
LGTM

**Comment by kaxil** [comment]
This is wrong @ernest-kr -- check https://github.com/astronomer/ap-airflow/commit/d2b1a21e067c371793d47ef5dcdf5d14cac94f83 

You need to update `.circleci/generate_circleci_config.py` file and a dev version here: `1.10.15-1.dev` instead of `1.10.15-1`

**Comment by kaxil** [comment]
You should also have not released a version: https://github.com/astronomer/airflow/releases/tag/v1.10.15%2Bastro.1 without an airflow version yet. 

We only push tags and a release on astronomer/airflow only when it is a final release and not a dev version. So we should have not created https://github.com/astronomer/airflow/releases/tag/v1.10.15%2Bastro.1

**Comment by kaxil** [comment]
And let's only merge PRs when the test pass please

**Pull request merged**
