### PR TITLE
Add Changelog info to readme

### PR DESCRIPTION
**Pull request by petedejoy**
**What this PR does / why we need it**:

This PR removes the (previously empty) top-level changelog in favor of changelogs at the version level. It also adds some info to our readme on where to find relevant changelogs.

### CODE REVIEW

**Comment by paolaperaza** [comment]
Noice @petedejoy - should we add a bullet point for 1.10.6 too since there's a folder for it in the repo, and then update with 1.10.10 as well?

**Comment by petedejoy** [comment]
Can def add 1.10.10. I thought about 1.10.6 but we don't have a changelog in there since we didn't cut an AC version with it.

**Comment by paolaperaza** [comment]
Ah yes, didn't see that - makes sense to keep out 1.10.6 then

**Comment by kaxil** [comment]
Converted to draft as merging any PR to ap-airflow will rebuild images and there is an open-issues regarding new image.

**Pull request merged**
