### PR TITLE
Add Changelog for 1.10.7-7

### PR DESCRIPTION
**Pull request by kaxil**
**What this PR does / why we need it**:

Adds Changelog for AC 1.10.7-7

### CODE REVIEW

**Comment by kaxil** [comment]
@petedejoy Let me know what format or what more information you would expect here

**Comment by kaxil** [comment]
> This is a great start, thanks @kaxil! Presumably, these fixes won't all have associated JIRA tickets, right? ie. if we need to hotfix something in our distro before it's upstreamed?

Yup, that is correct. And since Airflow has migrated to Github issues and removed the requirement of having an issue created before creating a PR, we won't have Jira/GH issue ID

**Comment by petedejoy** [comment]
Nice. I'm comfortable with merging this (and maybe a changelog for the other folders as well) as an MVP and then I can work with @paolaperaza to get these notes "operationalized" in our docs.

**Comment by kaxil** [comment]
@schnie Can we merge this please? I can't merge as it needs 1 reviewer to approve it

**Pull request merged**
