### PR TITLE
Enable building main builds on PR

### PR DESCRIPTION
**Pull request by kaxil**
closes https://github.com/astronomer/issues-airflow/issues/167

This PR will allow running "main" builds on PR too so it is easy to dev and test. It allow allows us to re-trigger a pipeline that ran on the `main` branch

### CODE REVIEW

**Comment by blag** [comment]
@jedcunningham and I were discussing this a bit and we figured that any dev build should probably skip needing approval. @kaxil What do you think?

**Comment by kaxil** [comment]
> @jedcunningham and I were discussing this a bit and we figured that any dev build should probably skip needing approval. @kaxil What do you think?

agree, will update

**Comment by kaxil** [comment]
> @jedcunningham and I were discussing this a bit and we figured that any dev build should probably skip needing approval. @kaxil What do you think?

Actually I think the change in the PR already takes care of it in the following line, wdyt?

https://github.com/astronomer/ap-airflow/blob/49368f40e1cdd44410df57fa4863cf43b5efeac1/.circleci/config.yml.j2#L143

**Comment by blag** [comment]
That handles the Slack notifications, but the approval task `pause_workflow` on line 39 will still tell CircleCI to require approval.

**Comment by kaxil** [comment]
> ```yaml
> name: Need-Approval-{{ airflow_version }}
> ```

Updated

**Comment by kaxil** [comment]
> That handles the Slack notifications, but the approval task `pause_workflow` on line 39 will still tell CircleCI to require approval:
> 
> ```yaml
>       - pause_workflow:
>           name: Need-Approval-{{ airflow_version }}
>           requires:
>             - Slack-Notification
>           type: approval
>           filters:
>             branches:
>               only:
>                 - master
> ```

Updated

**Comment by blag** [comment]
Alternative: #418.

**Pull request closed without merging**
